export interface Project {
  id: number;
  title: string;
  description: string;
  fullDescription: string;
  image: string;
  technologies: string[];
  features: string[];
  releaseDate: string;
  slug: string;
  externalLink: string;
  rotation: number;
}

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: "Joy Adventure",
    description:
      "An imaginative platform adventure game where players explore a colorful world, solve puzzles, collect items, and battle enemies. Featuring beautiful 2D graphics and smooth animations.",
    fullDescription:
      "Joy Adventure is a love letter to classic 2D platformers with a modern twist. Players step into the shoes of Joy, a curious young explorer who discovers a hidden world bursting with color, music, and mystery. The game features hand-crafted levels spread across five unique biomes — from sunlit meadows to crystal caverns — each with distinct environmental puzzles and secrets to uncover. Combat is accessible yet deep, with a timing-based parry system that rewards skillful play. The original soundtrack, composed with chiptune-inspired melodies, adapts dynamically to player actions, creating an immersive audio experience that evolves with each area explored.",
    image: "/images/Joy Adventure.jpeg",
    technologies: ["Unity", "C#", "2D Art", "Pixel Art"],
    features: [
      "5 unique hand-painted biomes",
      "Timing-based combat & parry system",
      "Dynamic adaptive soundtrack",
      "50+ collectible hidden secrets",
      "Boss battles per biome",
      "Unlockable character abilities",
    ],
    releaseDate: "2024-06-15",
    slug: "joy-adventure",
    externalLink: "https://store.steampowered.com/app/1234567",
    rotation: -0.5,
  },
  {
    id: 2,
    title: "Pixel Dungeon",
    description:
      "A retro-style dungeon crawler where players explore randomly generated dungeons, battle monsters, and collect equipment and items. Combining classic pixel art with modern game design.",
    fullDescription:
      "Pixel Dungeon channels the spirit of classic roguelikes while smoothing the rough edges that traditionally turned casual players away. Each run generates a completely unique dungeon layout with themed floors, random encounters, and procedurally placed loot. Death is permanent — but progression is persistent. Unlock new character classes, discover item synergies, and uncover the dark lore buried beneath the dungeon's depths. The pixel art style pays homage to 16-bit era classics while incorporating modern visual effects like dynamic lighting and particle systems that bring the underground world to life.",
    image: "/images/Pixel Dungeon.jpeg",
    technologies: ["Unity", "C#", "Pixel Art", "Procedural Generation"],
    features: [
      "Procedural dungeon generation",
      "6 unlockable character classes",
      "200+ unique items & weapons",
      "Permanent meta-progression",
      "Daily challenge runs",
      "Online leaderboards",
    ],
    releaseDate: "2024-09-20",
    slug: "pixel-dungeon",
    externalLink: "https://store.steampowered.com/app/2345678",
    rotation: 0.7,
  },
  {
    id: 3,
    title: "Space Exploration",
    description:
      "A sci-fi space exploration game where players can freely explore the universe, discover new planets and civilizations, trade, and battle. With vast cosmic maps, rich mission systems, and deep character progression.",
    fullDescription:
      "Space Exploration pushes the boundaries of what a small team can achieve with modern engines. Built in Unreal Engine 5, the game features a genuinely seamless galaxy with over 50 explorable star systems, each containing unique planets, space stations, and anomalies to investigate. Players captain their own vessel, managing crew, resources, and reputation across multiple factions. The mission system blends hand-crafted narrative missions with emergent encounters generated by a complex simulation layer tracking economy, politics, and ecology across the galaxy. Space combat uses a physics-based model where momentum, positioning, and loadout composition matter more than raw firepower.",
    image: "/images/Space Exploration.jpeg",
    technologies: ["Unreal Engine", "C++", "3D Modeling", "Space Physics"],
    features: [
      "50+ explorable star systems",
      "Deep faction reputation system",
      "Physics-based space combat",
      "Ship customization & upgrades",
      "Crew management simulation",
      "Emergent narrative events",
    ],
    releaseDate: "2025-03-10",
    slug: "space-exploration",
    externalLink: "https://store.steampowered.com/app/3456789",
    rotation: -0.3,
  },
  {
    id: 4,
    title: "Magic Farm",
    description:
      "A farming game blending simulation and RPG elements, where players manage their farm in a magical world, grow enchanted crops, raise mystical animals, interact with villagers, and complete various quests.",
    fullDescription:
      "Magic Farm reimagines the farming simulation genre through a fantasy lens. Players inherit a rundown magical farm in a village where crops have personalities, animals can talk, and the seasons are controlled by ancient spirits. Beyond standard farming mechanics — planting, watering, harvesting — players can crossbreed crops to create new magical variants, brew potions from harvested ingredients, and participate in seasonal festivals that change available activities and rewards. The relationship system with 20+ villagers features branching storylines, gift preferences, and unique cutscenes. Combat appears in the form of protecting your farm from magical pests and exploring nearby dungeons for rare seeds and artifacts.",
    image: "/images/Magic Farm.jpeg",
    technologies: ["Unity", "C#", "2D Art", "Simulation"],
    features: [
      "Magical crop crossbreeding system",
      "20+ romanceable villagers",
      "Seasonal festivals & events",
      "Potion brewing & crafting",
      "Light dungeon exploration",
      "Farm decoration & customization",
    ],
    releaseDate: "2025-06-05",
    slug: "magic-farm",
    externalLink: "https://store.steampowered.com/app/4567890",
    rotation: 0.4,
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return PROJECTS.find((project) => project.slug === slug);
}
